// Generated by LiveScript 1.3.1
(function(){
  var koaPassport, passportLocal, mongoose, LocalStrategy;
  koaPassport = require('koa-passport');
  passportLocal = require('passport-local');
  mongoose = require('mongoose');
  LocalStrategy = passportLocal.Strategy;
  koaPassport.serializeUser(function(user, done){
    return done(null, user);
  });
  koaPassport.deserializeUser(function(id, done){
    return db.user.model.findById(id, function(err, user){
      return done(err, user);
    });
  });
  koaPassport.use(new LocalStrategy(function(uid, pswd, done){
    console.log("Login: " + uid + " " + pswd);
    return db.user.query(uid, pswd, done);
  }));
}).call(this);
