// Generated by LiveScript 1.4.0
(function(){
  var path, webpack;
  path = require('path');
  webpack = require('webpack');
  module.exports = {
    // devtool: 'eval',
    entry: ['./src/public/js/dollast/app.ls'],
    output: {
      path: path.join(__dirname, 'public/js'),
      filename: 'app.js',
      publicPath: '/static/'
    },
     output: { 
       libraryTarget: "commonjs",
    },
    externals: [
  "react/addons",
  "redux",
  "redux-actions", 
  "react-redux", 
  "immutable", 
  "co", 
  "debug", 
  "superagent", 
  "superagent-promise", 
  "bluebird", 
  "react-highlight", 
  \react-router, 
  \redux-devtools/lib/react,
  \react-dropzone,
  \prelude-ls,
  \redux-promise,
  \redux-logger,
  \redux-devtools,
]
    ]
    // plugins: [
    //   new webpack.optimize.UglifyJsPlugin({
    //     compress: {
    //       warnings: false
    //     }
    //   })
    // ],
    module: {
      loaders: [{
        test: /\.ls$/,
        loaders: ['livescript'],
        // loader: 'babel',
        // include: path.join(__dirname, 'src/public/js/dollast')
      }]
    },
    resolve: {
      extensions: ["", ".ls", ".js"]
    }
  };
}).call(this);
