// Generated by LiveScript 1.3.1
(function(){
  var out$ = typeof exports != 'undefined' && exports || this;
  import$(out$, {
    concurrency: 3
  });
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
