// Generated by LiveScript 1.3.1
(function(){
  var run, out$ = typeof exports != 'undefined' && exports || this;
  out$.run = run = function(lang, code){
    return {
      time: Math.random() * 2,
      space: Math.random() * 128,
      result: Math.random() > 0.5
    };
  };
}).call(this);
