// Generated by LiveScript 1.3.1
(function(){
  var run, judge, out$ = typeof exports != 'undefined' && exports || this;
  out$.run = run = function(lang, code){
    return {
      time: Math.random() * 2,
      space: Math.random() * 128,
      result: Math.random()
    };
  };
  out$.judge = judge = function(lang, code, timeLmt, spaceLmt){};
}).call(this);
