// Generated by LiveScript 1.4.0
(function(){
  var path, webpack, vendors, config;
  path = require('path');
  webpack = require('webpack');
  vendors = ['react/addons', 'redux', 'redux-actions', 'react-redux', 'immutable', 'co', 'debug', 'superagent', 'superagent-promise', 'bluebird', 'react-highlight', 'react-router', 'redux-devtools/lib/react', 'react-dropzone', 'prelude-ls', 'redux-promise', 'redux-logger', 'redux-devtools'];
  module.exports = config = {
    debug: true,
    watch: true,
    entry: {
      app: './public/js/dollast/app',
      vendors: vendors
    },
    output: {
      path: path.join(__dirname, 'public/js'),
      filename: 'app.js',
      publicPath: '/static/'
    },
    plugins: [new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors.js')]
  };
}).call(this);
