// Generated by LiveScript 1.5.0
(function(){
  var path, webpack, vendors, config;
  path = require('path');
  webpack = require('webpack');
  vendors = ['co', 'debug', 'vue', 'vuex', 'vue-router', 'vue-resource', 'prelude-ls', 'moment'];
  module.exports = config = {
    debug: true,
    watch: true,
    entry: {
      app: './src/public/js/dollast/main.ls',
      vendors: vendors
    },
    resolve: {
      extensions: ['.js', '.vue', '.ls', "", '.coffee']
    },
    module: {
      loaders: [
        {
          test: /\.vue$/,
          loader: 'vue'
        }, {
          test: /\.ls$/,
          loader: 'vue-livescript-loader'
        }
      ]
    },
    output: {
      path: path.join(__dirname, 'public/js'),
      filename: 'app.js',
      publicPath: '/static/'
    },
    plugins: [new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors.js')]
  };
}).call(this);
