CPPFLAGS = -O2 --std=c++11
CPP = g++

all: sandboxer

test: AC TLE WA RE
	# ./sandboxer AC 1 128 128 10 test1.in test1.out > /dev/null && cat test1.out
	./sandboxer TLE 1 128 128 10 test1.in test1.out > /dev/null && cat test1.out
	# ./sandboxer WA 1 128 128 10 test1.in test1.out > /dev/null && cat test1.out
	# ./sandboxer RE 1 128 128 10 test1.in test1.out > /dev/null && cat test1.out
