// Generated by LiveScript 1.3.1
(function(){
  var core, co, util, src, lang;
  core = require('../core');
  co = require('co');
  util = require('util');
  src = '#include <iostream>\nusing namespace std;\n\nint main() {\n  int A, B;\n  for (int i = 1; i <= 100000000; ++i)\n    A += 1;\n  cin >> A >> B;\n  cout << A + B << endl;\n  return 0;\n}';
  lang = 'C++';
  core.compile(lang, src).then(function(val){
    return console.log("val: " + util.inspect(val));
  });
}).call(this);
